#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("DITS.HILI.WMS.Mobile.Resource", IsApplication=true)]

namespace DITS.HILI.WMS.Mobile
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int fork3 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int iconwms11 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int lo_m42 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int pa_m42 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int packingIco = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int qa_m42 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Shipping6 = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050041
			public const int btScan = 2131034177;
			
			// aapt resource value: 0x7f050052
			public const int btnConfirmReceive = 2131034194;
			
			// aapt resource value: 0x7f050044
			public const int btnFinish = 2131034180;
			
			// aapt resource value: 0x7f05000e
			public const int btnPutway = 2131034126;
			
			// aapt resource value: 0x7f050013
			public const int btnQA = 2131034131;
			
			// aapt resource value: 0x7f050037
			public const int btnQABack = 2131034167;
			
			// aapt resource value: 0x7f050038
			public const int btnQAFind = 2131034168;
			
			// aapt resource value: 0x7f050036
			public const int btnQAFinish = 2131034166;
			
			// aapt resource value: 0x7f05003b
			public const int btnQAProductConf = 2131034171;
			
			// aapt resource value: 0x7f05000d
			public const int btnReceive = 2131034125;
			
			// aapt resource value: 0x7f05003e
			public const int checkBox1 = 2131034174;
			
			// aapt resource value: 0x7f05004b
			public const int cmbLocation = 2131034187;
			
			// aapt resource value: 0x7f05004f
			public const int cmbStatus = 2131034191;
			
			// aapt resource value: 0x7f05004a
			public const int cmbStockUnit = 2131034186;
			
			// aapt resource value: 0x7f050050
			public const int cmbSubStatus = 2131034192;
			
			// aapt resource value: 0x7f05003c
			public const int editText1 = 2131034172;
			
			// aapt resource value: 0x7f05003d
			public const int editText2 = 2131034173;
			
			// aapt resource value: 0x7f05000c
			public const int gridLayout1 = 2131034124;
			
			// aapt resource value: 0x7f050010
			public const int gridLayout2 = 2131034128;
			
			// aapt resource value: 0x7f050012
			public const int gridLayout3 = 2131034130;
			
			// aapt resource value: 0x7f050046
			public const int imageProduct = 2131034182;
			
			// aapt resource value: 0x7f050007
			public const int imageView1 = 2131034119;
			
			// aapt resource value: 0x7f05001d
			public const int imgProduct = 2131034141;
			
			// aapt resource value: 0x7f050053
			public const int imgProductTmp = 2131034195;
			
			// aapt resource value: 0x7f050006
			public const int linearLayout1 = 2131034118;
			
			// aapt resource value: 0x7f05002d
			public const int linearLayout10 = 2131034157;
			
			// aapt resource value: 0x7f050008
			public const int linearLayout2 = 2131034120;
			
			// aapt resource value: 0x7f050019
			public const int linearLayout3 = 2131034137;
			
			// aapt resource value: 0x7f05001c
			public const int linearLayout4 = 2131034140;
			
			// aapt resource value: 0x7f050014
			public const int linearLayout5 = 2131034132;
			
			// aapt resource value: 0x7f05001f
			public const int linearLayout6 = 2131034143;
			
			// aapt resource value: 0x7f050020
			public const int linearLayout7 = 2131034144;
			
			// aapt resource value: 0x7f050022
			public const int linearLayout8 = 2131034146;
			
			// aapt resource value: 0x7f050023
			public const int linearLayout9 = 2131034147;
			
			// aapt resource value: 0x7f050030
			public const int linearLayout99 = 2131034160;
			
			// aapt resource value: 0x7f050042
			public const int listReceive = 2131034178;
			
			// aapt resource value: 0x7f05003f
			public const int listStstus = 2131034175;
			
			// aapt resource value: 0x7f050045
			public const int listViewReceive = 2131034181;
			
			// aapt resource value: 0x7f050039
			public const int lvQAJoblist = 2131034169;
			
			// aapt resource value: 0x7f050031
			public const int paBack = 2131034161;
			
			// aapt resource value: 0x7f050015
			public const int paBackToListBtn = 2131034133;
			
			// aapt resource value: 0x7f050018
			public const int paClearBtn = 2131034136;
			
			// aapt resource value: 0x7f050017
			public const int paConfrimBtn = 2131034135;
			
			// aapt resource value: 0x7f050034
			public const int putawayListView = 2131034164;
			
			// aapt resource value: 0x7f050033
			public const int reloadBtn = 2131034163;
			
			// aapt resource value: 0x7f050032
			public const int scanBtn = 2131034162;
			
			// aapt resource value: 0x7f05002f
			public const int scanTxt = 2131034159;
			
			// aapt resource value: 0x7f05000f
			public const int scrollView1 = 2131034127;
			
			// aapt resource value: 0x7f050011
			public const int scrollView2 = 2131034129;
			
			// aapt resource value: 0x7f050043
			public const int searchView1 = 2131034179;
			
			// aapt resource value: 0x7f05002c
			public const int spnPAReason = 2131034156;
			
			// aapt resource value: 0x7f05002e
			public const int spnPAWarehouses = 2131034158;
			
			// aapt resource value: 0x7f050003
			public const int textView1 = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int textView2 = 2131034113;
			
			// aapt resource value: 0x7f05003a
			public const int textView3 = 2131034170;
			
			// aapt resource value: 0x7f050021
			public const int textView4 = 2131034145;
			
			// aapt resource value: 0x7f050057
			public const int textView6 = 2131034199;
			
			// aapt resource value: 0x7f05005a
			public const int textView8 = 2131034202;
			
			// aapt resource value: 0x7f050047
			public const int txtConvertionQTY = 2131034183;
			
			// aapt resource value: 0x7f050048
			public const int txtConvertionUnit = 2131034184;
			
			// aapt resource value: 0x7f05004e
			public const int txtEXPDate = 2131034190;
			
			// aapt resource value: 0x7f050005
			public const int txtLocation = 2131034117;
			
			// aapt resource value: 0x7f05004d
			public const int txtMFGDate = 2131034189;
			
			// aapt resource value: 0x7f05002a
			public const int txtPAConfLoaction = 2131034154;
			
			// aapt resource value: 0x7f050028
			public const int txtPALocation = 2131034152;
			
			// aapt resource value: 0x7f05002b
			public const int txtPALot = 2131034155;
			
			// aapt resource value: 0x7f05001a
			public const int txtPAPallet = 2131034138;
			
			// aapt resource value: 0x7f050024
			public const int txtPAQTY = 2131034148;
			
			// aapt resource value: 0x7f050026
			public const int txtPARemainQTY = 2131034150;
			
			// aapt resource value: 0x7f050027
			public const int txtPARemainUnit = 2131034151;
			
			// aapt resource value: 0x7f050029
			public const int txtPASgLocation = 2131034153;
			
			// aapt resource value: 0x7f050025
			public const int txtPAUnit = 2131034149;
			
			// aapt resource value: 0x7f05001b
			public const int txtPAproductCode = 2131034139;
			
			// aapt resource value: 0x7f05001e
			public const int txtPAproductName = 2131034142;
			
			// aapt resource value: 0x7f050009
			public const int txtProduct = 2131034121;
			
			// aapt resource value: 0x7f05004c
			public const int txtProductLot = 2131034188;
			
			// aapt resource value: 0x7f05005e
			public const int txtQAConfirmQTY1 = 2131034206;
			
			// aapt resource value: 0x7f05005f
			public const int txtQAConfirmQTY2 = 2131034207;
			
			// aapt resource value: 0x7f05005c
			public const int txtQADate = 2131034204;
			
			// aapt resource value: 0x7f050035
			public const int txtQAFind = 2131034165;
			
			// aapt resource value: 0x7f050060
			public const int txtQALocation = 2131034208;
			
			// aapt resource value: 0x7f05005b
			public const int txtQANoItem = 2131034203;
			
			// aapt resource value: 0x7f05005d
			public const int txtQAProduct = 2131034205;
			
			// aapt resource value: 0x7f050061
			public const int txtQAStatus = 2131034209;
			
			// aapt resource value: 0x7f05000a
			public const int txtQty = 2131034122;
			
			// aapt resource value: 0x7f050000
			public const int txtRecDate = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int txtRecNo = 2131034114;
			
			// aapt resource value: 0x7f050040
			public const int txtReceiveNo = 2131034176;
			
			// aapt resource value: 0x7f050051
			public const int txtRemark = 2131034193;
			
			// aapt resource value: 0x7f050049
			public const int txtStockQTY = 2131034185;
			
			// aapt resource value: 0x7f050004
			public const int txtSup = 2131034116;
			
			// aapt resource value: 0x7f05000b
			public const int txtUnit = 2131034123;
			
			// aapt resource value: 0x7f050016
			public const int txtWH = 2131034134;
			
			// aapt resource value: 0x7f050055
			public const int txvLocationFromTmp = 2131034197;
			
			// aapt resource value: 0x7f050056
			public const int txvPalletTmp = 2131034198;
			
			// aapt resource value: 0x7f050054
			public const int txvProductTmp = 2131034196;
			
			// aapt resource value: 0x7f050058
			public const int txvUnitRemTmp = 2131034200;
			
			// aapt resource value: 0x7f050059
			public const int txvUnitTmp = 2131034201;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int listReceive = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int listReceiveItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int PutawayItemDetail = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int PutawayListItem = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int QAJobListItem = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int QAProductDetail = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Receive = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int ReceiveItem = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int ReceiveItemConfirm = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int tempPutawayProduct = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int tempQAJobList = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int tempQAProductList = 2130903052;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int ReceiveTitle = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
